resources:
  - name: divijawebhook
    type: IncomingWebhook
    configuration:
      webhookName: divijawebhook
      
  - name: release_bundle_test
    type: ReleaseBundle
    configuration:
      sourceDistribution: clouddistribution
      name: ${app_name}
      version: ${app_version}

  # Signed version of the same release bundle
  - name: signed_bundle_test
    type: ReleaseBundle
    configuration:
      sourceDistribution: clouddistribution
      name: ${app_name}
      version: ${app_version}

  # Distribution rules
  - name: distribution_rules_test
    type: DistributionRule
    configuration:
      sourceDistribution: clouddistribution
      serviceName: "*"
      siteName: "*"
      cityName: "*"
      countryCodes:
        - "US" 
        
  - name: aql_test
    type: Aql
    configuration:
      sourceArtifactory: artifactory
      query: items.find({"$and":[{"$or":[{"repo":{"$eq":"generic-local"}},{"repo":{"$eq":"generic-test"}}]},{"$or":[{"name":{"$match":"${app_name}-*-${app_version}*"}},{"name":{"$match":"${app_name}_${app_version}_*"}}]}]})


pipelines:
  - name: divija_build
    steps:
    - name: ExtractFileName
      type: Bash
      configuration:
        inputResources:
          - name: divijawebhook
        outputResources:
          - name: aql_test
      execution:
          onExecute:
            - set_payload divijawebhook "$res_divijawebhook_payload"
            - echo "$res_divijawebhook_payload" | jq '.' > payload.json
            - set_payload divijawebhook payload.json --file
            - cat payload.json
            - read_json payload.json "data.name"
            - add_run_variables distribution_filename=$(read_json payload.json "data.name")
            - echo $distribution_filename
            - add_run_variables app_name=$(echo $distribution_filename | awk -F_ '{print $1}')
            - add_run_variables app_version=$(echo $distribution_filename | awk -F_ '{print $2}')
            - echo $app_name 	
            - echo $app_version
            
    - name: releasebundle
      type: CreateReleaseBundle
      configuration:
        releaseBundleName: ${app_name}
        releaseBundleVersion: ${app_version}
        dryRun: false
        sign: false
        description: "Application deb distribution"
        inputResources:
          - name: aql_test
            trigger: true
        outputResources:
          - name: release_bundle_test
        releaseNotes:
          syntax: markdown
          content: |
            ## Heading
              * Bullet
              * Points
              
    - name: signreleasebundle
      type: SignReleaseBundle
      configuration:
        inputResources:
          - name: release_bundle_test
        outputResources:
          - name: signed_bundle_test

    - name: distributereleasebundle
      type: DistributeReleaseBundle
      configuration:
        dryRun: false
        inputResources:
          - name: signed_bundle_test
          - name: distribution_rules_test
